version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: >
      postgres -c 'shared_preload_libraries=pg_stat_statements'

  init_db:
    image: postgres
    depends_on:
      - db
    command: >
      /bin/bash -c "
      sleep 10;
      echo 'CREATE DATABASE paiement_db;' | PGPASSWORD=admin psql -h db -U postgres;
      echo 'CREATE DATABASE client_db;' | PGPASSWORD=admin psql -h db -U postgres;
      echo 'CREATE DATABASE commande_db;' | PGPASSWORD=admin psql -h db -U postgres;
      echo 'CREATE DATABASE produit_db;' | PGPASSWORD=admin psql -h db -U postgres;
      "

volumes:
  db_data:

